language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

env:
  - DB=mysql
  - DB=pgsql

before_script:
  - composer update --ignore-platform-reqs

script: vendor/phpunit/phpunit/phpunit --coverage-text tests/
